#  k3d create --name k3d --api-port 6551 --publish 80:80 --workers 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-skaffold-deployment
  labels:
    app: boot-skaffold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boot-skaffold
  template:
    metadata:
      name: boot-skaffold-deployment
      labels:
        app: boot-skaffold
    spec:
      containers:
        - name: boot-skaffold-deployment
          image: daggerok/boot-skaffold
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: boot-skaffold-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: boot-skaffold
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: boot-skaffold-ingress
  #annotations:
  #  ingress.kubernetes.io/ssl-redirect: "false"
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: boot-skaffold-service
              servicePort: 80
#    - host: ololo.trololo.com
#      http:
#        paths:
#          - backend:
#              serviceName: boot-skaffold-service
#              servicePort: 80
