---
apiVersion: v1
kind: Pod
metadata:
  name: boot-skaffold
  labels:
    app: boot-skaffold
spec:
  containers:
    - name: boot-skaffold
      image: daggerok/boot-skaffold
      imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-skaffold
  labels:
    app: boot-skaffold
spec:
  selector:
    matchLabels:
      app: boot-skaffold
  replicas: 1
  template:
    metadata:
      name: boot-skaffold
      labels:
        app: boot-skaffold
    spec:
      containers:
        - name: boot-skaffold
          image: daggerok/boot-skaffold
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boot-skaffold
  labels:
    app: boot-skaffold
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: boot-skaffold
