apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: boot-skaffold
build:
  artifacts:
    - image: daggerok/boot-skaffold
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
    - k8s.yaml
