apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: boot-skaffold
build:
  artifacts:
    - image: daggerok/boot-skaffold
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
    #- k8s-pod.yaml
    #- k8s-all.yaml
    #- k8s.yaml
    - k8s-k3d.yaml
